# Generated by Django 2.2.5 on 2019-12-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagebody',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
