# Generated by Django 2.2.5 on 2019-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dabout', '0002_aboutpagebody_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagebody',
            name='id_about',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
