# Generated by Django 2.2.5 on 2019-12-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=2, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=10, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('last_donate_date', models.CharField(blank=True, max_length=50, null=True)),
                ('any_diseases', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('allergies', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('cardiac', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'NO')], max_length=4, null=True)),
                ('bleeding_disorders', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('hbsAg_hcv_hIV', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
            ],
        ),
    ]
