# Generated by Django 2.2.8 on 2019-12-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorlist',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donorlist',
            name='cardiac',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True),
        ),
    ]
